name: Ant CI sample 
on: push 
jobs: 
  ant-build: 
    runs-on: ubuntu-latest
    container: frekele/ant:latest
    steps: 
    - name: checkout 
      uses: actions/checkout@v2
    - name: setup java 8
      uses: actions/setup-java@v2
      with: 
        distribution: 'temurin'
        java-version: '11'
    - name: ant build 
      run: |
        ant clean
        ant compile 
        ant jar 
        ant run  